-- COMPUTE_STATUS.sql

create or replace FUNCTION COMPUTE_STATUS_LICENSEPOOL(IS_CANCELLED VARCHAR2, START_DATE TIMESTAMP, END_DATE TIMESTAMP) RETURN CHAR DETERMINISTIC
IS
  STATUS CHAR(6);
BEGIN
  IF (IS_CANCELLED = 'Y') THEN STATUS:= 'C';
    ELSE IF (START_DATE > SYSDATE) THEN STATUS:= 'P';
      ELSE IF (END_DATE > SYSDATE) THEN STATUS:= 'A';
        ELSE STATUS:= 'E';
        END IF;
    END IF;
  END IF;
 RETURN STATUS;
END;

/

