-- LICENSEPOOL_ORGANIZATION.sql

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM user_constraints WHERE constraint_name='LP_ORG_LICENSEPOOL_FK_1' AND table_name='LICENSEPOOL_ORGANIZATION' AND constraint_type='R';

IF x = 0 THEN
   EXECUTE IMMEDIATE 
   '
      ALTER TABLE "LICENSEPOOL_ORGANIZATION"
	  ADD CONSTRAINT "LP_ORG_LICENSEPOOL_FK_1"
	  FOREIGN KEY ("LICENSEPOOL_ID")
	  REFERENCES "LICENSEPOOL" ("LICENSEPOOL_ID") ENABLE
   ';   
   
END IF;

END;

/
