-- LICENSEPOOL_ORGANIZATION.sql

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM user_tables WHERE TABLE_NAME = 'LICENSEPOOL_ORGANIZATION';

IF x = 0 THEN
   EXECUTE IMMEDIATE
   '
   CREATE TABLE "LICENSEPOOL_ORGANIZATION"
   (
      "ORGANIZATION_LP_ID" CHAR(32) NOT NULL ENABLE,
      "LICENSEPOOL_ID" CHAR(32) NOT NULL ENABLE,
      "ORGANIZATION_ID" VARCHAR2(32) NOT NULL ENABLE,
      "USED_QUANTITY" NUMBER(16) NOT NULL ENABLE,
      "ORGANIZATION_LEVEL" NUMBER(3) NOT NULL ENABLE,
      "DENYNEWSUBSCRIPTION" CHAR(8) NOT NULL ENABLE,
      "DT_ADDED" TIMESTAMP (6) NOT NULL ENABLE,
      "DT_MODIFIED" TIMESTAMP (6) NOT NULL ENABLE,
      "MODIFIED_BY" VARCHAR2(32) NOT NULL ENABLE,
      "ADDED_BY" VARCHAR2(32) NOT NULL ENABLE,
      CONSTRAINT "IDX_LICENSEPOOL_ORGANIZATION_1" PRIMARY KEY ("ORGANIZATION_LP_ID") ENABLE
   )

  ';
END IF;

END;

/


--  Removing duplicate records having same combination of LicensePoolId and OrganizationId. 

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM LICENSEPOOL_ORGANIZATION;

IF x > 0 THEN

EXECUTE IMMEDIATE
'
DELETE FROM LICENSEPOOL_ORGANIZATION LP_ORG WHERE ROWID != ( SELECT MIN(ROWID) FROM LICENSEPOOL_ORGANIZATION WHERE LICENSEPOOL_ID = LP_ORG.LICENSEPOOL_ID AND ORGANIZATION_ID = LP_ORG.ORGANIZATION_ID )
';

END IF;

END;

/


-- Enforcing a Unique Key Constraint on LicensePoolId and OrganizationId.

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM user_indexes WHERE index_name='LICENSEPOOL_ORGANIZATION_UK' AND table_name='LICENSEPOOL_ORGANIZATION' AND index_type='NORMAL';

IF x = 0 THEN
   EXECUTE IMMEDIATE
   '
      CREATE UNIQUE INDEX "LICENSEPOOL_ORGANIZATION_UK"
      ON "LICENSEPOOL_ORGANIZATION" ("LICENSEPOOL_ID","ORGANIZATION_ID")
   ';
END IF;

END;

/