-- ORDERLINEITEM_LP.sql

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM user_tables WHERE TABLE_NAME = 'LICENSEPOOL_ORDERLINEITEM';


IF x = 0 THEN
   EXECUTE IMMEDIATE
   '
  CREATE TABLE "LICENSEPOOL_ORDERLINEITEM"
   (
      "ORDERLINEITEM_LP_ID" CHAR(32) NOT NULL ENABLE,
      "LICENSEPOOL_ID" CHAR(32) NOT NULL ENABLE,
      "ORDERLINEITEM_ID" CHAR(32) NOT NULL ENABLE,
      "DT_ADDED" TIMESTAMP (6) NOT NULL ENABLE,
      "DT_MODIFIED" TIMESTAMP (6) NOT NULL ENABLE,
      "MODIFIED_BY" VARCHAR2(32) NOT NULL ENABLE,
      "ADDED_BY" VARCHAR2(32) NOT NULL ENABLE,
      CONSTRAINT "IDX_LICENSEPOOL_ORDERLINE_1" PRIMARY KEY ("LICENSEPOOL_ID","ORDERLINEITEM_ID") ENABLE,
      CONSTRAINT "FK_LICENSEPOOL_ORDERLINE_1" FOREIGN KEY ("LICENSEPOOL_ID") REFERENCES "LICENSEPOOL" ("LICENSEPOOL_ID") ENABLE
   )
  ';
END IF;

END;

/
