package com.pearson.ed.lp.stub.mock;

import com.pearson.ed.lp.message.LicensePoolByOrganizationIdRequest;
import com.pearson.ed.lp.message.LicensePoolResponse;
import com.pearson.ed.lp.stub.api.LicensePoolLifeCycleClient;

/**
 * Mock implementation of LicensePoolLifeCycleClient interface. Wraps another mock instance generated by a mock library
 * like EasyMock. This is to support Spring Integration configuration wiring.
 * 
 * @author ULLOYNI
 * 
 */
public class MockLicensePoolLifeCycleClient implements LicensePoolLifeCycleClient {

	private LicensePoolLifeCycleClient mockClient;

	@Override
	public LicensePoolResponse getLicensePoolsByOrganizationId(LicensePoolByOrganizationIdRequest request) {
		return mockClient.getLicensePoolsByOrganizationId(request);
	}

	public LicensePoolLifeCycleClient getMockClient() {
		return mockClient;
	}

	public void setMockClient(LicensePoolLifeCycleClient mockClient) {
		this.mockClient = mockClient;
	}

}
