CREATE OR REPLACE FUNCTION COMPUTE_STATUS_LICENSEPOOL(START_DATE TIMESTAMP, END_DATE TIMESTAMP) RETURN CHAR DETERMINISTIC
IS
  STATUS CHAR(6);
BEGIN
	IF (START_DATE > SYSDATE) THEN STATUS:= 'P';
		ELSE IF (END_DATE > SYSDATE) THEN STATUS:= 'A';
			ELSE STATUS:= 'E';
        END IF;
    END IF;
 RETURN STATUS;
END;