PROMPT Running script ORDERLINEITEM_LP.sql

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM user_tables WHERE TABLE_NAME = 'LICENSEPOOL_ORDERLINEITEM';
_

IF x = 0 THEN
   EXECUTE IMMEDIATE 
   '
   CREATE TABLE "LICENSEPOOL_ORDERLINEITEM" 
   (
      "ORDERLINEITEM_LP_ID" VARCHAR2(32) NOT NULL ENABLE,
      "LICENSEPOOL_ID" VARCHAR2(32) NOT NULL ENABLE, 
      "ORDERLINEITEM_ID" VARCHAR2(32) NOT NULL ENABLE,
      "DT_ADDED" TIMESTAMP (6) NOT NULL ENABLE, 
      "DT_MODIFIED" TIMESTAMP (6) NOT NULL ENABLE, 
      "MODIFIED_BY" VARCHAR2(32) NOT NULL ENABLE, 
      "ADDED_BY" VARCHAR2(32) NOT NULL ENABLE,
      CONSTRAINT "IDX_LICENSEPOOL_ORDERLINE_1" PRIMARY KEY ("LICENSEPOOL_ID","ORDERLINEITEM_ID") ENABLE      
   )
  ';
END IF;

END;

/
