PROMPT Running script Organization_LP.sql

DECLARE x NUMBER;
BEGIN
SELECT COUNT(*) INTO x FROM user_tables WHERE TABLE_NAME = 'LICENSEPOOL_ORGANIZATION';

IF x = 0 THEN
   EXECUTE IMMEDIATE 
   '
   CREATE TABLE "LICENSEPOOL_ORGANIZATION" 
   (
      "ORGANIZATION_LP_ID" CHAR(32) NOT NULL ENABLE,
      "LICENSEPOOL_ID" CHAR(32) NOT NULL ENABLE, 
      "ORGANIZATION_ID" VARCHAR2(32) NOT NULL ENABLE,
      "USED_QUANTITY" NUMBER(16) NOT NULL ENABLE,
      "ORGANIZATION_LEVEL" NUMBER(3) NOT NULL ENABLE,
      "DENYNEWSUBSCRIPTION" CHAR(8) NOT NULL ENABLE,
      "DT_ADDED" TIMESTAMP (6) NOT NULL ENABLE, 
      "DT_MODIFIED" TIMESTAMP (6) NOT NULL ENABLE, 
      "MODIFIED_BY" VARCHAR2(32) NOT NULL ENABLE, 
      "ADDED_BY" VARCHAR2(32) NOT NULL ENABLE,
      CONSTRAINT "IDX_LICENSEPOOL_ORGANIZATION_1" PRIMARY KEY ("ORGANIZATION_LP_ID") ENABLE,
      CONSTRAINT "FK_LICENSEPOOL_ORGANIZATION_1" FOREIGN KEY ("LICENSEPOOL_ID") REFERENCES "LICENSEPOOL" ("LICENSEPOOL_ID") ENABLE
   )
   
  ';
END IF;

END;

/
