# licensepool acceptance-tests gemfile
source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://rumba.ci.dev.pearsoncmg.com/gem-proxy"

gem "rspec-expectations", "~>2.6.0"
gem "uuid"
gem "cucumber"
gem "atdd-common", ">=12.6.4.20120301141050"
