-- GRANT_PRIVILEGES

BEGIN

-- TABLES

EXECUTE IMMEDIATE 'grant all ON LICENSEPOOL to @user@';
EXECUTE IMMEDIATE 'grant all ON LICENSEPOOL_ORDERLINEITEM to @user@';
EXECUTE IMMEDIATE 'grant all ON LICENSEPOOL_ORGANIZATION to @user@';

-- FUNCTIONS

EXECUTE IMMEDIATE 'grant all ON COMPUTE_STATUS_LICENSEPOOL to @user@';

-- SEQUENCES

EXECUTE IMMEDIATE 'grant all ON RUMBA_PRODUCT_ENT_SEQ to @user@';
EXECUTE IMMEDIATE 'grant all ON RUMBA_PRODUCT_SEQ to @user@';
EXECUTE IMMEDIATE 'grant all ON RUMBA_RESOURCE_ENT_SEQ to @user@';
EXECUTE IMMEDIATE 'grant all ON RUMBA_RESOURCE_SEQ to @user@';

END;

/
